language: objective-c

install: 
  - "install/virtualbox.sh"
  - "install/vagrant.sh"
  - "install/travis-cookbooks.sh"

before_script: 
  - "vboxmanage --version"
  - "vagrant --version"
  - "echo Travis Cookbooks Rev: $(cat travis-cookbook-rev)"

script: true

