language: objective-c

install: 
  - "install/virtualbox.sh"
  - "install/vagrant.sh"

before_script: 
  - "echo VirtualBox Version: $(vboxmanage --version)"
  - "echo Vagrant Version: $(vagrant --version)"

script: true

